version: "3"

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.local.com'
    container_name: gitlab
    ports:
      - '8888:80'
      - '4430:443'
      - '220:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  gitlab-runner-1:
    image: 'gitlab/gitlab-runner:latest'
    hostname: 'gitlab-runner-1.local.com'
    restart: always
    container_name: gitlab-runner-1
    links:
      - gitlab

  gitlab-runner-2:
    image: 'gitlab/gitlab-runner:latest'
    hostname: 'gitlab-runner-2.local.com'
    restart: always
    container_name: gitlab-runner-2
    links:
      - gitlab

volumes:
  gitlab-config:
    external: true
  gitlab-logs:
    external: true
  gitlab-data:
    external: true