version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  jumpserver:
    image: jumpserver/jumpserver:0.5.0-beta2
    container_name: jumpserver
    restart: always
    ports:
      - 9998:8080
    depends_on:
      - redis

  coco:
    image: jumpserver/coco:0.5.0-beta2
    container_name: coco
    restart: always
    ports:
      - 2222:2222
    depends_on:
      - jumpserver
      
  luna:
    image: jumpserver/luna:0.5.0-beta2
    container_name: luna
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - jumpserver

