version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "lgt633744"
      TZ: "Asia/Shanghai"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      
volumes:
  mysql-data:
    external: true

