version: "3"
services:
  pingcap_tipd_1:
    image: 'pingcap/pd:latest'
    container_name: tipd1
    command:
      - "--name=pd1"
      - "--data-dir=/data/pd1"
      - "--client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://192.168.1.78:2371"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--advertise-peer-urls=http://192.168.1.78:2381"
      - "--initial-cluster=pd1=http://192.168.1.78:2381,pd2=http://192.168.1.78:2382,pd3=http://192.168.1.78:2383"
    ports:
      - '2371:2379'
      - '2381:2380'
    volumes:
      - 'pingcap-data:/data'

  pingcap_tipd_2:
    image: 'pingcap/pd:latest'
    container_name: tipd2
    command:
      - "--name=pd2"
      - "--data-dir=/data/pd2"
      - "--client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://192.168.1.78:2372"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--advertise-peer-urls=http://192.168.1.78:2382"
      - "--initial-cluster=pd1=http://192.168.1.78:2381,pd2=http://192.168.1.78:2382,pd3=http://192.168.1.78:2383"
    ports:
      - '2372:2379'
      - '2382:2380'
    volumes:
      - 'pingcap-data:/data'

  pingcap_tipd_3:
    image: 'pingcap/pd:latest'
    container_name: tipd3
    command:
      - "--name=pd3"
      - "--data-dir=/data/pd3"
      - "--client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://192.168.1.78:2373"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--advertise-peer-urls=http://192.168.1.78:2383"
      - "--initial-cluster=pd1=http://192.168.1.78:2381,pd2=http://192.168.1.78:2382,pd3=http://192.168.1.78:2383"
    ports:
      - '2373:2379'
      - '2383:2380'
    volumes:
      - 'pingcap-data:/data'

  pingcap_tikv_1:
    image: 'pingcap/tikv:latest'
    container_name: tikv1
    command:
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=192.168.1.78:20161"
      - "--data-dir=/data/tikv1"
      - "--pd=192.168.1.78:2371,192.168.1.78:2372,192.168.1.78:2373"
    ports:
      - '20161:20160'
    volumes:
      - 'pingcap-data:/data'

  pingcap_tikv_2:
    image: 'pingcap/tikv:latest'
    container_name: tikv2
    command:
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=192.168.1.78:20162"
      - "--data-dir=/data/tikv2"
      - "--pd=192.168.1.78:2371,192.168.1.78:2372,192.168.1.78:2373"
    ports:
      - '20162:20160'
    volumes:
      - 'pingcap-data:/data'

  pingcap_tikv_3:
    image: 'pingcap/tikv:latest'
    container_name: tikv3
    command:
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=192.168.1.78:20163"
      - "--data-dir=/data/tikv3"
      - "--pd=192.168.1.78:2371,192.168.1.78:2372,192.168.1.78:2373"
    ports:
      - '20163:20160'
    volumes:
      - 'pingcap-data:/data'

  pingcap_tidb:
    image: 'pingcap/tidb:latest'
    container_name: tidb
    command:
      - "--store=tikv"
      - "--path=192.168.1.78:2371,192.168.1.78:2372,192.168.1.78:2373"
    ports:
      - '4000:4000'
      - '10080:10080'

volumes:
  pingcap-data:
